# K9s — Kubernetes TUI configuration
# Skin: stock by default. On DMS hosts the skin is `dank`, generated by DMS's
# matugen into ~/.config/k9s/skins/dank.yaml.
{ config, lib, ... }:

let
  # On hosts running the DMS desktop shell, colors are owned by DMS (matugen)
  # so the k9s skin is regenerated on every wallpaper/theme change. The
  # dank-material-shell module is only imported on DMS hosts, so its `enable`
  # flag is the signal. See dms/matugen for the template that writes the skin.
  isDms = (config.programs.dank-material-shell or { }).enable or false;
  # Active skin: DMS hosts use the matugen-generated `dank` skin; non-DMS
  # hosts omit the key so k9s uses its stock skin.
  uiSettings =
    if isDms then {
      enableMouse = false;
      headless = false;
      logoless = false;
      crumbsless = false;
      reactive = false;
      noIcons = false;
      defaultsToFullScreen = false;
      # Active skin: set explicitly so DMS hosts can use the matugen-generated
      # `dank` skin.
      skin = "dank";
    } else {
      enableMouse = false;
      headless = false;
      logoless = false;
      crumbsless = false;
      reactive = false;
      noIcons = false;
      defaultsToFullScreen = false;
    };
in
{
  programs.k9s = {
    enable = true;

    settings = {
      k9s = {
        liveViewAutoRefresh = false;
        screenDumpDir = "~/.local/state/k9s/screen-dumps";
        refreshRate = 2;
        maxConnRetry = 5;
        readOnly = false;
        noExitOnCtrlC = false;
        portForwardAddress = "localhost";
        ui = uiSettings;
        skipLatestRevCheck = false;
        disablePodCounting = false;
        shellPod = {
          image = "busybox:1.35.0";
          namespace = "default";
          limits = {
            cpu = "100m";
            memory = "100Mi";
          };
        };
        imageScans = {
          enable = false;
          exclusions = {
            namespaces = [ ];
            labels = { };
          };
        };
        logger = {
          tail = 100;
          buffer = 5000;
          sinceSeconds = -1;
          textWrap = false;
          disableAutoscroll = false;
          showTime = false;
        };
        thresholds = {
          cpu = {
            critical = 90;
            warn = 70;
          };
          memory = {
            critical = 90;
            warn = 70;
          };
        };
      };
    };

    aliases = {
      aliases = {
        dp = "deployments";
        sec = "v1/secrets";
        jo = "jobs";
        cr = "clusterroles";
        crb = "clusterrolebindings";
        ro = "roles";
        rb = "rolebindings";
        np = "networkpolicies";
      };
    };
  };
}
