# OpenCode — AI coding agent configuration
# Deploys global config, TUI settings, global AGENTS.md, and skills via
# ~/.config/opencode/. Theme: stock by default. On DMS hosts the theme is
# `dank`, generated by DMS's matugen.
{ config, pkgs, ... }:

let
  # On hosts running the DMS desktop shell, colors are owned by DMS (matugen)
  # so themes applied in DMS propagate to OpenCode. The dank-material-shell
  # module is only imported on DMS hosts, so its `enable` flag is the signal.
  isDms = (config.programs.dank-material-shell or { }).enable or false;
  skillsDir = ./skills;
  # OpenCode theme name: DMS uses the matugen-generated `dank` theme (deployed
  # by the dms/matugen module to ~/.config/opencode/themes/dank.json). Non-DMS
  # hosts use OpenCode's stock theme.
  opencodeTheme = if isDms then "dank" else null;
in
{
  # Install OpenCode CLI
  home.packages = with pkgs; [
    opencode
  ];

  # OpenCode global config
  xdg.configFile."opencode/opencode.json".force = true;
  xdg.configFile."opencode/opencode.json".text = builtins.toJSON (
    {
      "$schema" = "https://opencode.ai/config.json";
      instructions = [ "docs/Contributing/AGENTS.md" ];
    }
    // (if opencodeTheme != null then { theme = opencodeTheme; } else { })
  );

  # Global AGENTS.md — personal preferences, always loaded regardless of CWD
  xdg.configFile."opencode/AGENTS.md" = {
    force = true;
    source = ./global-agents.md;
  };

  # Skills — on-demand reference material loaded by the agent when relevant
  xdg.configFile."opencode/skills/nix-modules/SKILL.md" = {
    force = true;
    source = "${skillsDir}/nix-modules/SKILL.md";
  };
  xdg.configFile."opencode/skills/docs-sync/SKILL.md" = {
    force = true;
    source = "${skillsDir}/docs-sync/SKILL.md";
  };
  xdg.configFile."opencode/skills/upstream-mgmt/SKILL.md" = {
    force = true;
    source = "${skillsDir}/upstream-mgmt/SKILL.md";
  };
  xdg.configFile."opencode/skills/makefile-convention/SKILL.md" = {
    force = true;
    source = "${skillsDir}/makefile-convention/SKILL.md";
  };

  # TUI config: select the theme
  xdg.configFile."opencode/tui.json".force = true;
  xdg.configFile."opencode/tui.json".text = builtins.toJSON (
    {
      "$schema" = "https://opencode.ai/tui.json";
    }
    // (if opencodeTheme != null then { theme = opencodeTheme; } else { })
  );
}
