# yazi — terminal file manager with image preview support
#
# Appearance: yatline header/status bars, full-border, git indicators.
# Theme: stock by default. On DMS hosts the theme.toml and yatline palette are
# generated by DMS's matugen into ~/.config/yazi/ (regenerated on every theme
# change).
{ pkgs, lib, config, ... }:
let
  isDms = (config.programs.dank-material-shell or { }).enable or false;
in
{
  programs.yazi = {
    enable = true;
    enableZshIntegration = true;
    shellWrapperName = "y";

    # ── Plugins (from nixpkgs) ──────────────────────────────────────
    plugins = {
      full-border = pkgs.yaziPlugins.full-border;
      git = pkgs.yaziPlugins.git;
      yatline = pkgs.yaziPlugins.yatline;
    };

    # ── Plugin initialisation (init.lua) ────────────────────────────
    # Load order: palette → yatline → full-border → git. DMS hosts get a
    # matugen-generated palette at ~/.config/yazi/dank-palette.lua (same
    # semantic roles as yatline's palettes); non-DMS hosts get yatline's
    # built-in stock theme.
    initLua = ''
      ${lib.optionalString isDms ''
        local ok, dank_palette = pcall(dofile, os.getenv("HOME") .. "/.config/yazi/dank-palette.lua")
        local theme = ok and dank_palette
      ''}

      -- Header + status bars
      require("yatline"):setup({
        ${lib.optionalString isDms "theme = theme,"}

        section_separator = { open = "", close = "" },
        part_separator    = { open = "", close = "" },
        inverse_separator = { open = "", close = "" },

        show_background = true,

        header_line = {
          left = {
            section_a = {
              { type = "line", name = "tabs", params = { "left" } },
            },
            section_b = {},
            section_c = {},
          },
          right = {
            section_a = {
              { type = "string", name = "date", params = { "%A, %d %B %Y" } },
            },
            section_b = {
              { type = "string", name = "date", params = { "%X" } },
            },
            section_c = {},
          },
        },

        status_line = {
          left = {
            section_a = {
              { type = "string", name = "tab_mode" },
            },
            section_b = {
              { type = "string", name = "hovered_size" },
            },
            section_c = {
              { type = "string", name = "hovered_path" },
              { type = "coloreds", name = "count" },
            },
          },
          right = {
            section_a = {
              { type = "string", name = "cursor_position" },
            },
            section_b = {
              { type = "string", name = "cursor_percentage" },
            },
            section_c = {
              { type = "string", name = "hovered_file_extension", params = { true } },
              { type = "coloreds", name = "permissions" },
            },
          },
        },
      })

      -- Bordered panes (load AFTER yatline)
      require("full-border"):setup({
        type = ui.Border.ROUNDED,
      })

      -- Git file-status indicators
      require("git"):setup()
    '';

    # ── Layout & behaviour (yazi.toml) ──────────────────────────────
    settings = {
      mgr = {
        ratio = [
          1
          4
          3
        ];
        show_hidden = false;
        show_symlink = true;
        sort_by = "natural";
        sort_dir_first = true;
        sort_sensitive = false;
        linemode = "size";
        scrolloff = 5;
      };
      preview = {
        tab_size = 2;
        wrap = "no";
      };
      plugin = {
        prepend_fetchers = [
          {
            group = "git";
            run = "git";
            url = "*";
          }
          {
            group = "git";
            run = "git";
            url = "*/";
          }
        ];
      };
    };

    # ── Theme (theme.toml) ─────────────────────────────────────────
    # Left unset so yazi uses its stock theme. On DMS hosts matugen owns
    # ~/.config/yazi/theme.toml (deployed by the dms/matugen module).
  };

  # Keep `yy` as a stable shortcut while avoiding function/alias collisions in
  # shells that already define `yy`.
  programs.zsh.shellAliases.yy = "y";
}
