# Starship prompt — stock prompt by default. On DMS hosts the entire config is
# generated by DMS's matugen into ~/.config/starship.toml (starship reads a
# single config file, no include mechanism), so settings stay empty there.
{ ... }:

{
  programs.starship = {
    enable = true;
    enableZshIntegration = false;

    # Empty settings → HM writes no starship.toml, so starship uses its stock
    # prompt. On DMS hosts matugen owns ~/.config/starship.toml (HM still sets
    # STARSHIP_CONFIG to that path); non-DMS hosts get the stock prompt.
    settings = { };
  };
}
